// Biblioteca de recetas de referencia. Cada una está contrastada con su fuente (enlace en `fuente`)
// el 8 de octubre de 2026. Las cantidades, tiempos y temperaturas son los del autor; solo hay
// dos cosas que añade la app y que se presentan como tales:
//   - `clicsC40`: punto de partida orientativo en tu Comandante C40 a partir de la molienda
//     que describe el autor (el autor no da clics).
//   - La duración de pasos que el autor no cronometra (remover, girar), indicada en los pasos.
// Las instrucciones no llevan gramos: el temporizador muestra los pesos escalados a tu dosis.
// No hay recetas de Chemex, Kalita ni Clever porque no he encontrado una fuente de referencia
// clara y verificable; puedes crear las tuyas.
import type { Receta } from '../modelo';

const base = { creado: 0, actualizado: 0, referencia: true } as const;

export const RECETAS_REFERENCIA: Receta[] = [
  {
    ...base,
    id: 'ref-hoffmann-v60-1taza',
    nombre: 'V60 de una taza',
    metodo: 'v60',
    autor: 'James Hoffmann',
    resumen: 'Para 15 g: bloom y cuatro vertidos cortos con pausas, y unos 3 minutos en total. La más cómoda para tu dosis habitual.',
    fuente: { titulo: 'James Hoffmann · «A Better 1 Cup V60 Technique» (YouTube)', url: 'https://www.youtube.com/watch?v=1oB1oDrDkHM' },
    dosis: 15,
    agua: 250,
    temperatura: 100,
    molienda: 'Media-fina',
    clicsC40: [20, 24],
    filtro: 'Papel Hario blanco',
    fases: [
      { nombre: 'Bloom', duracion: 45, aguaHasta: 50, instruccion: 'Moja todo el café. A los 10 s da un giro suave al dripper y deja reposar.' },
      { nombre: 'Vertido 1', duracion: 25, aguaHasta: 100, instruccion: 'Vierte en unos 15 s y espera.' },
      { nombre: 'Vertido 2', duracion: 20, aguaHasta: 150, instruccion: 'Vierte en unos 10 s y espera.' },
      { nombre: 'Vertido 3', duracion: 20, aguaHasta: 200, instruccion: 'Vierte en unos 10 s y espera.' },
      { nombre: 'Vertido 4', duracion: 10, aguaHasta: 250, instruccion: 'Último vertido, en unos 10 s.' },
      { nombre: 'Giro y drenaje', duracion: 60, instruccion: 'Un giro suave para aplanar la cama y deja drenar. Objetivo: terminar hacia 3:00. Pulsa Terminar cuando acabe.' },
    ],
    tiempoObjetivo: [165, 200],
    consejos: [
      'Agua recién hervida, sobre todo con tuestes claros.',
      'Vierte por bloques con pausas cortas, como marca el temporizador.',
      'Hoffmann usa la V60 de plástico porque conserva mejor el calor que la de cerámica o vidrio.',
      'Si el drenaje acaba mucho después de 3:00, muele más grueso; si acaba mucho antes, más fino.',
    ],
  },
  {
    ...base,
    id: 'ref-hoffmann-v60',
    nombre: 'V60 · técnica definitiva',
    metodo: 'v60',
    autor: 'James Hoffmann',
    resumen: 'La receta de V60 más conocida: bloom y dos vertidos grandes. Pensada para 30 g (dos tazas).',
    fuente: { titulo: 'HARIO USA · «James Hoffmann – Ultimate V60 Technique»', url: 'https://www.hario-usa.com/blogs/recipes-and-more-from-friends/james-hoffmann-uitimate-v60-technique' },
    dosis: 30,
    agua: 500,
    temperatura: 100,
    molienda: 'Media-fina',
    clicsC40: [22, 26],
    filtro: 'Papel Hario blanco',
    fases: [
      { nombre: 'Bloom', duracion: 45, aguaHasta: 60, instruccion: 'Haz un hueco en el centro del café y vierte en espiral desde el centro. Gira el dripper hasta que no queden grumos.' },
      { nombre: 'Primer vertido', duracion: 30, aguaHasta: 300, instruccion: 'Vierte en 30 s hasta el 60 % del total.' },
      { nombre: 'Segundo vertido', duracion: 30, aguaHasta: 500, instruccion: 'Vierte el resto en 30 s, algo más despacio que antes.' },
      { nombre: 'Remover y girar', duracion: 15, instruccion: 'Remueve con una cuchara una vez en un sentido y otra en el contrario, y da un giro suave al dripper.' },
      { nombre: 'Drenaje', duracion: 90, instruccion: 'Deja drenar. Objetivo: terminar hacia 3:30. Pulsa Terminar cuando acabe.' },
    ],
    tiempoObjetivo: [195, 225],
    consejos: [
      'El agua, cuanto más caliente mejor, sobre todo con tuestes claros.',
      'Para el bloom, mejor girar el dripper que remover.',
      'El tiempo de drenaje cambia con el filtro y la temperatura: úsalo para ajustar la molienda.',
      'Para una sola taza, Hoffmann tiene una versión específica: «V60 de una taza».',
    ],
  },
  {
    ...base,
    id: 'ref-kasuya-46',
    nombre: 'Método 4:6',
    metodo: 'v60',
    autor: 'Tetsu Kasuya · campeón del mundo de Brewers Cup 2016',
    resumen: 'Cinco vertidos: el primer 40 % del agua decide dulzor o acidez y el 60 % final, la intensidad. Molienda gruesa.',
    fuente: { titulo: 'HARIO UK · Entrevista a Tetsu Kasuya (receta 4:6)', url: 'https://www.hario.co.uk/blogs/hario-ambassadors/hario-v60-recipe-interview-with-hario-ambassador-tetsu-kasuya' },
    dosis: 20,
    agua: 300,
    temperatura: 92,
    molienda: 'Gruesa',
    clicsC40: [28, 32],
    filtro: 'Papel Hario blanco',
    fases: [
      { nombre: 'Vertido 1', duracion: 45, aguaHasta: 50, instruccion: 'Este vertido marca el carácter: menos agua aquí da más dulzor; más agua, más acidez.' },
      { nombre: 'Vertido 2', duracion: 45, aguaHasta: 120, instruccion: 'Completa el 40 % del agua.' },
      { nombre: 'Vertido 3', duracion: 40, aguaHasta: 180, instruccion: 'Empieza el 60 %: tres vertidos iguales.' },
      { nombre: 'Vertido 4', duracion: 30, aguaHasta: 240, instruccion: 'Segundo vertido igual.' },
      { nombre: 'Vertido 5', duracion: 50, aguaHasta: 300, instruccion: 'Último vertido. A los 3:30 retira el dripper aunque quede agua y pulsa Terminar.' },
    ],
    tiempoObjetivo: [200, 225],
    consejos: [
      'Los dos primeros vertidos suman siempre el 40 % del agua. Si quieres más dulzor, haz el primero más pequeño; si quieres más acidez, más grande.',
      'El 60 % restante se reparte en vertidos iguales según la intensidad que busques.',
      'Kasuya usa la V60 cerámica modelo Tetsu Kasuya, que drena más despacio. Con una V60 normal puede drenar antes: si te sale floja, muele algo más fino.',
      'Agua a 92 °C.',
    ],
  },
  {
    ...base,
    id: 'ref-hoffmann-aeropress',
    nombre: 'AeroPress · técnica definitiva',
    metodo: 'aeropress',
    autor: 'James Hoffmann',
    resumen: 'Sin invertir ni remover: verter, tapar con el émbolo, esperar, girar y presionar suave.',
    fuente: { titulo: 'James Hoffmann · «The Ultimate AeroPress Technique» (YouTube)', url: 'https://www.youtube.com/watch?v=j6VlT_jUVPc' },
    dosis: 11,
    agua: 200,
    temperatura: 99,
    molienda: 'Fina a media-fina',
    clicsC40: [14, 18],
    filtro: 'Papel AeroPress',
    fases: [
      { nombre: 'Verter', duracion: 10, aguaHasta: 200, instruccion: 'AeroPress en posición normal sobre la taza. Vierte todo el agua mojando todo el café.' },
      { nombre: 'Tapar y esperar', duracion: 110, instruccion: 'Mete el émbolo 1 cm para hacer vacío y que no gotee. Espera sin tocar.' },
      { nombre: 'Girar', duracion: 30, instruccion: 'Sujetando émbolo y cuerpo, da un giro suave. Espera 30 s.' },
      { nombre: 'Presionar', duracion: 30, instruccion: 'Presiona suave y constante hasta el final, en unos 30 s. Pulsa Terminar.' },
    ],
    tiempoObjetivo: [170, 200],
    consejos: [
      'No hace falta enjuagar el filtro ni precalentar la AeroPress.',
      'Girar en lugar de remover: menos agitación y más fácil de repetir igual.',
      'Usa poca dosis a propósito (11 g para 200 g).',
    ],
  },
  {
    ...base,
    id: 'ref-hoffmann-prensa',
    nombre: 'Prensa francesa · técnica definitiva',
    metodo: 'prensa',
    autor: 'James Hoffmann',
    resumen: 'Infusión de 4 minutos y un reposo largo para que el poso baje: taza limpia sin filtro de papel.',
    fuente: { titulo: 'James Hoffmann · «The Ultimate French Press Technique» (YouTube)', url: 'https://www.youtube.com/watch?v=st571DYYTR8' },
    dosis: 30,
    agua: 500,
    temperatura: 100,
    molienda: 'Media',
    clicsC40: [24, 30],
    filtro: 'Malla metálica',
    fases: [
      { nombre: 'Verter', duracion: 15, aguaHasta: 500, instruccion: 'Vierte todo el agua recién hervida mojando todo el café.' },
      { nombre: 'Infusión', duracion: 225, instruccion: 'Espera sin tapar ni remover hasta los 4:00.' },
      { nombre: 'Romper la costra', duracion: 45, instruccion: 'Remueve la costra de la superficie con una cuchara y retira la espuma y lo que flote.' },
      { nombre: 'Reposo', duracion: 300, instruccion: 'Espera al menos 5 minutos (hasta 8) para que el poso baje al fondo.' },
      { nombre: 'Servir', duracion: null, instruccion: 'Baja el émbolo solo hasta la superficie, sin empujar el poso, y sirve despacio. Pulsa Terminar.' },
    ],
    tiempoObjetivo: [570, 780],
    consejos: [
      'No presiones hasta el fondo: el émbolo solo hace de colador.',
      'Cuanto más esperes antes de servir (de 5 a 8 minutos), menos poso llega a la taza.',
    ],
  },
  {
    ...base,
    id: 'ref-hoffmann-moka',
    nombre: 'Moka · técnica definitiva',
    metodo: 'moka',
    autor: 'James Hoffmann',
    resumen: 'Agua ya caliente, café sin prensar, fuego suave con la tapa abierta y cortar a tiempo.',
    fuente: { titulo: 'James Hoffmann · «The Ultimate Moka Pot Technique» (búsqueda en YouTube)', url: 'https://www.youtube.com/results?search_query=James+Hoffmann+The+Ultimate+Moka+Pot+Technique' },
    dosis: 15,
    agua: 150,
    molienda: 'Algo más gruesa que para espresso',
    clicsC40: [11, 15],
    filtro: 'Filtro de la cafetera',
    fases: [
      { nombre: 'Montar', duracion: null, instruccion: 'Calienta el agua aparte y échala en la base sin pasar la válvula. Llena el cacillo a ras sin prensar y cierra con un trapo (quema). Pulsa Siguiente al ponerla al fuego.' },
      { nombre: 'Fuego suave', duracion: null, instruccion: 'Fuego suave y tapa abierta. Pulsa Siguiente cuando empiece a salir el café.' },
      { nombre: 'Salida', duracion: null, instruccion: 'Cuando el chorro se aclare o empiece a borbotear, retira del fuego y enfría la base con agua fría. Pulsa Terminar.' },
    ],
    consejos: [
      'Las cantidades dependen de tu cafetera: cacillo lleno a ras y agua justo por debajo de la válvula.',
      'El agua ya caliente acorta el tiempo al fuego y evita sabores a quemado.',
      'No prenses el café en el cacillo.',
      'Cortar a tiempo y enfriar la base frena la extracción y evita el amargor del final.',
    ],
  },
  {
    ...base,
    id: 'ref-espresso-1-2',
    nombre: 'Espresso de partida 1:2',
    metodo: 'espresso',
    autor: 'La Marzocco Home',
    resumen: 'El punto de partida estándar para ajustar cualquier café: el doble de peso en taza en 25-30 s.',
    fuente: { titulo: 'La Marzocco Home · «How to Make Espresso»', url: 'https://home.lamarzoccousa.com/how-to-make-espresso/' },
    dosis: 18,
    rendimiento: 36,
    molienda: 'Fina',
    filtro: 'Cesta de serie',
    fases: [{ nombre: 'Extracción', duracion: null, instruccion: 'Pulsa Primera gota cuando caiga y Parar al llegar al peso objetivo.' }],
    tiempoObjetivo: [25, 30],
    consejos: [
      'Ajusta la molienda hasta caer en 25-30 s.',
      'Cambia una sola cosa cada vez: dosis, salida o molienda.',
      'La guía no fija temperatura: usa la de tu máquina.',
    ],
  },
];
